#include <WiFi.h>
#include <WiFiMulti.h>
#include <WiFiManager.h>
#include <WebServer.h>
#include <ESPmDNS.h>
#include <qrcode.h>  // ESP-IDF QR encoder, bundled with the ESP32 core
#include <Preferences.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>
#include <ArduinoJson.h>
#include <TFT_eSPI.h>
#include <TJpg_Decoder.h>
#include <AnimatedGIF.h>
#include <new>
#include "secrets.h"
#include "gif_data.h"  // generated by tools/gif2h.py

#ifndef GIF_BG_COLOR  // headers from older gif2h.py runs
#define GIF_BG_COLOR TFT_BLACK
#define GIF_BG_LIGHT 0
#endif

#ifndef GETSONGBPM_API_KEY
#define GETSONGBPM_API_KEY ""  // no key: BPM lookup is skipped and the GIF plays at its own speed
#endif

// Layout for 320x480 portrait: text on top, art along the bottom
const int SCREEN_W = 320, SCREEN_H = 480;
const int ART_SIZE = 300, ART_X = (SCREEN_W - ART_SIZE) / 2, ART_Y = SCREEN_H - ART_SIZE - 10;
const int TEXT_X = 10, TEXT_Y = 8, TEXT_W = SCREEN_W - 2 * TEXT_X;
const int WAVE_H = 18, WAVE_Y = ART_Y - 6 - WAVE_H;
const int BAR_W = 6, BAR_GAP = 4, BAR_COUNT = (TEXT_W + BAR_GAP) / (BAR_W + BAR_GAP);
const uint32_t WAVE_FRAME_MS = 80;
const uint32_t POLL_MS = 5000;
const uint16_t TOUCH_Z_MIN = 600;  // raw touch pressure that counts as a tap
// The ESP32's BOOT button (GPIO 0) switches pages, for when touch isn't wired.
// Held for 1.5 s it shows the Spotify account page; held during boot, it adds a
// Wi-Fi network
const int BOOT_BUTTON = 0;

TFT_eSPI tft;
// Spotify polling runs as its own task on core 0 so the wave and GIF keep moving
// during slow HTTPS requests; this lock keeps the two from drawing at once
SemaphoreHandle_t tftLock;
TaskHandle_t spotifyTaskHandle;

enum Page : uint8_t { PAGE_NOW_PLAYING, PAGE_GIF, PAGE_ACCOUNT };
volatile Page page = PAGE_NOW_PLAYING;  // only loop() changes it, under tftLock
volatile bool forceRedraw = false;      // back on the now-playing page; redraw everything
volatile bool gifPageDirty = false;     // song or BPM changed while on the GIF page

const char* SETUP_AP = "DeskPlayer-Setup";
const int PORTAL_TIMEOUT_S = 180;
// docs/callback.html on GitHub Pages: forwards Spotify's sign-in result back to
// this board. Must be listed under Redirect URIs in the Spotify app's settings.
const char* SPOTIFY_REDIRECT = "https://natung15.github.io/Phoneweight/callback.html";
Preferences prefs;
String refreshToken;  // from the Spotify sign-in page, kept in flash

// Every network set up through the portal is kept (newest first, oldest dropped
// past MAX_NETWORKS), and the board joins whichever of them is in range
const int MAX_NETWORKS = 5;
String savedSsid[MAX_NETWORKS], savedPass[MAX_NETWORKS];
int savedCount = 0;
WiFiMulti wifiMulti;

String accessToken;
uint32_t tokenFetchedAt = 0, tokenTtlMs = 0;
String currentArtUrl, lastInfo, bpmKey;
String curTitle, curArtist;  // shared with the GIF page; guarded by tftLock
volatile bool isPlaying = false, showWave = false;
volatile int bpm = 0;  // 0 = unknown
uint32_t lastFrame = 0;
uint8_t barH[BAR_COUNT];  // height each bar is currently drawn at
bool touchOk = false;

// The GIF decoder needs ~22 KB, so it only exists while its page is showing
AnimatedGIF* gif = nullptr;
int gifX, gifY;
uint32_t gifLoopMs = 0;  // one loop at the GIF's own speed
uint32_t nextFrameAt = 0;
uint16_t gifLine[SCREEN_W];

const uint16_t SPOTIFY_GREEN = 0x1DCA;  // #1DB954
uint16_t panelBg = TFT_BLACK;           // darkened average colour of the current art
uint32_t sumR, sumG, sumB, sumN;

// TJpg_Decoder hands over decoded blocks; push them straight to the screen
bool tftOutput(int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t* bitmap) {
  if (y >= tft.height()) return false;
  // Sample the art so the background can be tinted to match
  for (uint32_t i = 0; i < (uint32_t)w * h; i += 7) {
    uint16_t c = (bitmap[i] >> 8) | (bitmap[i] << 8);  // undo setSwapBytes
    sumR += c >> 11;
    sumG += (c >> 5) & 0x3F;
    sumB += c & 0x1F;
    sumN++;
  }
  tft.pushImage(x, y, w, h, bitmap);
  return true;
}

// ---- Loading screen ----
// A spinner task animates while setup() blocks on Wi-Fi and Spotify. Any other
// screen stops it first; the task re-checks the flag under tftLock, so it never
// draws over whatever replaced it.
volatile bool loadingActive = false;
const int SPIN_X = SCREEN_W / 2, SPIN_Y = 250, SPIN_R = 26, SPIN_DOTS = 10;

void stopLoading() {
  loadingActive = false;
}

// Big "DeskPlayer" title, a spinner, and what it's doing
void showLoading(const String& message, const String& hint) {
  xSemaphoreTake(tftLock, portMAX_DELAY);
  tft.fillScreen(TFT_BLACK);
  tft.setTextDatum(TC_DATUM);
  tft.setFreeFont(&FreeSansBold18pt7b);
  tft.setTextColor(TFT_WHITE);
  tft.drawString("DeskPlayer", SCREEN_W / 2, 140);
  tft.setFreeFont(&FreeSans9pt7b);
  tft.setTextColor(TFT_LIGHTGREY);
  tft.drawString(message, SCREEN_W / 2, SPIN_Y + SPIN_R + 30);
  String lines[3];
  int y = SPIN_Y + SPIN_R + 60;
  tft.setTextColor(TFT_DARKGREY);
  int n = wrapText(hint, TEXT_W, 3, lines);
  for (int i = 0; i < n; i++, y += tft.fontHeight()) tft.drawString(lines[i], SCREEN_W / 2, y);
  tft.setTextDatum(TL_DATUM);
  loadingActive = true;
  xSemaphoreGive(tftLock);
}

void spinnerTask(void*) {
  uint8_t head = 0;
  for (;;) {
    vTaskDelay(pdMS_TO_TICKS(90));
    if (!loadingActive) continue;
    xSemaphoreTake(tftLock, portMAX_DELAY);
    if (loadingActive) {
      for (int i = 0; i < SPIN_DOTS; i++) {
        int age = (head - i + SPIN_DOTS) % SPIN_DOTS;  // 0 = leading dot
        uint16_t c = age == 0 ? SPOTIFY_GREEN : age < 3 ? TFT_LIGHTGREY : age < 6 ? TFT_DARKGREY : 0x2104;
        float a = 2 * PI * i / SPIN_DOTS;
        tft.fillCircle(SPIN_X + SPIN_R * sinf(a), SPIN_Y - SPIN_R * cosf(a), 4, c);
      }
      head = (head + 1) % SPIN_DOTS;
    }
    xSemaphoreGive(tftLock);
  }
}

// Centred status text on a black screen, for boot and Wi-Fi setup
void showStatus(const String& heading, const String& detail, const String& hint) {
  xSemaphoreTake(tftLock, portMAX_DELAY);
  drawStatus(heading, detail, hint);
  xSemaphoreGive(tftLock);
}

// Same, for callers already holding tftLock
void drawStatus(const String& heading, const String& detail, const String& hint) {
  stopLoading();
  tft.fillScreen(TFT_BLACK);
  tft.setTextDatum(TC_DATUM);
  String lines[4];
  int y = 150;
  tft.setFreeFont(&FreeSansBold12pt7b);
  tft.setTextColor(TFT_WHITE);
  int n = wrapText(heading, TEXT_W, 4, lines);
  for (int i = 0; i < n; i++, y += tft.fontHeight()) tft.drawString(lines[i], SCREEN_W / 2, y);
  y += 12;
  tft.setFreeFont(&FreeSansBold18pt7b);
  tft.setTextColor(SPOTIFY_GREEN);
  if (detail.length()) {
    tft.drawString(detail, SCREEN_W / 2, y);
    y += tft.fontHeight() + 12;
  }
  tft.setFreeFont(&FreeSans9pt7b);
  tft.setTextColor(TFT_LIGHTGREY);
  n = wrapText(hint, TEXT_W, 4, lines);
  for (int i = 0; i < n; i++, y += tft.fontHeight()) tft.drawString(lines[i], SCREEN_W / 2, y);
  tft.setTextDatum(TL_DATUM);
}

void loadNetworks() {
  savedCount = min((int)prefs.getUChar("nets", 0), MAX_NETWORKS);
  for (int i = 0; i < savedCount; i++) {
    savedSsid[i] = prefs.getString(("ssid" + String(i)).c_str(), "");
    savedPass[i] = prefs.getString(("pass" + String(i)).c_str(), "");
    wifiMulti.addAP(savedSsid[i].c_str(), savedPass[i].c_str());
  }
  Serial.printf("%d saved Wi-Fi network(s)\n", savedCount);
}

// Put the network we're on at the front of the saved list
void rememberNetwork(const String& ssid, const String& pass) {
  if (ssid.isEmpty() || (savedCount && savedSsid[0] == ssid && savedPass[0] == pass)) return;
  bool known = false;
  for (int i = 0; i < savedCount; i++) known |= savedSsid[i] == ssid && savedPass[i] == pass;
  if (!known) wifiMulti.addAP(ssid.c_str(), pass.c_str());  // WiFiMulti keeps duplicates

  String ssids[MAX_NETWORKS] = {ssid}, passes[MAX_NETWORKS] = {pass};
  int n = 1;
  for (int i = 0; i < savedCount && n < MAX_NETWORKS; i++) {
    if (savedSsid[i] == ssid) continue;  // same network with an old password
    ssids[n] = savedSsid[i];
    passes[n++] = savedPass[i];
  }
  savedCount = n;
  for (int i = 0; i < n; i++) {
    savedSsid[i] = ssids[i];
    savedPass[i] = passes[i];
    prefs.putString(("ssid" + String(i)).c_str(), ssids[i]);
    prefs.putString(("pass" + String(i)).c_str(), passes[i]);
  }
  prefs.putUChar("nets", n);
  Serial.printf("Saved Wi-Fi network %s (%d saved)\n", ssid.c_str(), n);
}

void restartAfterTimeout() {
  Serial.println("Wi-Fi setup timed out; restarting");
  showStatus("Setup timed out", "", "Restarting...");
  delay(2000);
  ESP.restart();
}

// Swap the one-time code from Spotify's sign-in page for a refresh token
bool exchangeAuthCode(const String& code) {
  WiFiClientSecure client;
  client.setInsecure();
  HTTPClient http;
  http.begin(client, "https://accounts.spotify.com/api/token");
  http.setAuthorization(SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET);
  http.addHeader("Content-Type", "application/x-www-form-urlencoded");
  int status = http.POST("grant_type=authorization_code&code=" + urlEncode(code) +
                         "&redirect_uri=" + urlEncode(SPOTIFY_REDIRECT));
  String body = http.getString();
  http.end();
  JsonDocument doc;
  if (status != 200 || deserializeJson(doc, body) || !doc["refresh_token"].is<const char*>()) {
    Serial.printf("Spotify sign-in failed: %d %s\n", status, body.c_str());
    return false;
  }
  refreshToken = doc["refresh_token"].as<String>();
  prefs.putString("refresh", refreshToken);
  accessToken = doc["access_token"].as<String>();
  tokenTtlMs = (doc["expires_in"] | 3600) * 1000UL - 60000;
  tokenFetchedAt = millis();
  Serial.println("Signed in to Spotify; saved the refresh token");
  return true;
}

// Takes the address Spotify's sign-in ended on (with ?code=), or a refresh
// token. Returns what went wrong, or "" once a new account is saved.
String applySpotifyEntry(String entry) {
  entry.trim();
  if (entry.isEmpty()) return "Paste the address first";
  if (entry.indexOf("error=") >= 0) return "Spotify sign-in was cancelled";
  int i = entry.indexOf("code=");
  if (i >= 0) {
    String code = entry.substring(i + 5);
    int stop = code.indexOf('&');
    if (stop >= 0) code = code.substring(0, stop);
    stop = code.indexOf('#');
    if (stop >= 0) code = code.substring(0, stop);
    return exchangeAuthCode(code) ? "" : "Spotify sign-in failed. Tap Sign in again for a new address";
  }
  if (entry.startsWith("http")) return "That address has no Spotify sign-in code";
  refreshToken = entry;
  prefs.putString("refresh", refreshToken);
  Serial.println("Saved new Spotify refresh token");
  return "";
}

String htmlEscape(String s) {
  s.replace("&", "&amp;");
  s.replace("<", "&lt;");
  s.replace(">", "&gt;");
  return s;
}

String spotifyPage(const String& message) {
  String signInUrl = "https://accounts.spotify.com/authorize?client_id=" + String(SPOTIFY_CLIENT_ID) +
                     "&amp;response_type=code&amp;scope=user-read-currently-playing&amp;show_dialog=true" +
                     "&amp;redirect_uri=" + urlEncode(SPOTIFY_REDIRECT) +
                     "&amp;state=" + urlEncode("http://" + WiFi.localIP().toString());  // where to come back to
  String page =
      "<!DOCTYPE html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'>"
      "<title>DeskPlayer Spotify</title><style>"
      "body{font-family:-apple-system,sans-serif;max-width:480px;margin:auto;padding:16px;background:#121212;color:#eee}"
      ".btn{display:block;box-sizing:border-box;width:100%;text-align:center;padding:14px;border:0;border-radius:24px;"
      "font-size:18px;font-weight:600;text-decoration:none;background:#1DB954;color:#000}"
      "summary{margin-top:28px;color:#aaa}"
      "textarea{width:100%;box-sizing:border-box;height:90px;font-size:15px;border-radius:8px;padding:8px}"
      ".err{background:#5a1d1d;padding:10px;border-radius:8px}</style></head><body>"
      "<h2>Connect Spotify</h2>";
  if (message.length()) page += "<p class='err'>" + htmlEscape(message) + "</p>";
  if (refreshToken.length()) page += "<p>This display already has a Spotify account. Signing in here replaces it.</p>";
  page +=
      "<p>Tap the button, sign in, and tap <b>Agree</b>. You'll come straight back here.</p>"
      "<a class='btn' href='" + signInUrl + "'>Sign in to Spotify</a>"
      "<details><summary>Didn't come back?</summary>"
      "<p>Copy the text from the \"Almost done\" page (or its whole address) and paste it here:</p>"
      "<form method='post' action='/'><textarea name='code' autocapitalize='none' autocorrect='off' "
      "placeholder='https://...callback.html?code=...'></textarea>"
      "<p><button class='btn' type='submit'>Finish</button></p></form></details>";
  return page + "</body></html>";
}

// The Spotify sign-in page is served on the home network all the time, at
// http://deskplayer.local or the board's IP, so the account can be switched
// whenever. loop() answers the phone; spotifyTask does the actual sign-in,
// since it's the only task that touches the tokens.
WebServer server(80);
enum SignIn : uint8_t { SIGNIN_IDLE, SIGNIN_PENDING, SIGNIN_DONE, SIGNIN_FAILED };
volatile SignIn signIn = SIGNIN_IDLE;
String signInEntry, signInError;

const char* PAGE_STYLE =
    "<meta name='viewport' content='width=device-width,initial-scale=1'><body style='font-family:"
    "-apple-system,sans-serif;max-width:480px;margin:auto;padding:16px;background:#121212;color:#eee'>";

void setupWebServer() {
  server.on("/", HTTP_GET, []() {
    // Back from Spotify via docs/callback.html with ?code= or ?error=
    if (server.hasArg("error")) {
      server.send(200, "text/html", spotifyPage("Spotify sign-in was cancelled"));
      return;
    }
    if (server.hasArg("code") && signIn != SIGNIN_PENDING) {
      signInEntry = "code=" + server.arg("code");
      signIn = SIGNIN_PENDING;
      xTaskNotifyGive(spotifyTaskHandle);
      server.sendHeader("Location", "/wait");
      server.send(303);
      return;
    }
    server.send(200, "text/html", spotifyPage(""));
  });
  server.on("/", HTTP_POST, []() {
    if (signIn != SIGNIN_PENDING) {
      signInEntry = server.arg("code");
      signIn = SIGNIN_PENDING;
      xTaskNotifyGive(spotifyTaskHandle);
    }
    server.sendHeader("Location", "/wait");
    server.send(303);
  });
  server.on("/wait", []() {
    if (signIn == SIGNIN_PENDING) {
      server.send(200, "text/html", String(PAGE_STYLE) + "<meta http-equiv='refresh' content='1'><h2>Signing in...</h2>");
    } else if (signIn == SIGNIN_FAILED) {
      server.send(200, "text/html", spotifyPage(signInError));
    } else {
      server.send(200, "text/html", String(PAGE_STYLE) + "<h2>Done</h2><p>Spotify is connected. "
                                                         "Play something and it shows up on the display.</p>");
    }
  });
  server.onNotFound([]() {
    server.sendHeader("Location", "/");
    server.send(302);
  });
  MDNS.begin("deskplayer");
  MDNS.addService("http", "tcp", 80);
  server.begin();
  Serial.printf("Spotify page: http://%s or http://deskplayer.local\n", WiFi.localIP().toString().c_str());
}

// Runs on spotifyTask
void handleSignIn() {
  if (signIn != SIGNIN_PENDING) return;
  if (page == PAGE_ACCOUNT) showLoading("Signing in to Spotify...", "");
  String error = applySpotifyEntry(signInEntry);
  if (error.isEmpty()) {
    // New account: drop the old one's song so the screen redraws from scratch
    bpmKey = "";
    forceRedraw = true;
    signIn = SIGNIN_DONE;
    if (page == PAGE_ACCOUNT) switchPage();
  } else {
    signInError = error;
    signIn = SIGNIN_FAILED;
    xSemaphoreTake(tftLock, portMAX_DELAY);
    if (page == PAGE_ACCOUNT) drawAccountPage();  // the phone shows what went wrong
    xSemaphoreGive(tftLock);
  }
}

// QR codes are drawn from esp_qrcode's callback, which takes no context
int qrTop, qrBottom;
const int QR_MAX_PX = 230;

void drawQr(esp_qrcode_handle_t qr) {
  int n = esp_qrcode_get_size(qr);
  int scale = min(7, QR_MAX_PX / (n + 8));  // 4-module white border each side
  int total = (n + 8) * scale, x0 = (SCREEN_W - total) / 2;
  tft.fillRect(x0, qrTop, total, total, TFT_WHITE);
  for (int y = 0; y < n; y++)
    for (int x = 0; x < n; x++)
      if (esp_qrcode_get_module(qr, x, y))
        tft.fillRect(x0 + (x + 4) * scale, qrTop + (y + 4) * scale, scale, scale, TFT_BLACK);
  qrBottom = qrTop + total;
}

// A QR code for the Spotify page, plus its address for typing; caller holds tftLock
void drawAccountPage() {
  stopLoading();
  bool hasAccount = refreshToken.length();
  String ip = WiFi.localIP().toString();
  tft.fillScreen(TFT_BLACK);
  tft.setTextDatum(TC_DATUM);
  tft.setFreeFont(&FreeSansBold12pt7b);
  tft.setTextColor(TFT_WHITE);
  tft.drawString(hasAccount ? "Switch Spotify account" : "Sign in to Spotify", SCREEN_W / 2, 16);
  tft.setFreeFont(&FreeSans9pt7b);
  tft.setTextColor(TFT_LIGHTGREY);
  tft.drawString("Scan with your phone camera", SCREEN_W / 2, 48);

  qrTop = qrBottom = 76;
  esp_qrcode_config_t cfg = ESP_QRCODE_CONFIG_DEFAULT();
  cfg.display_func = drawQr;
  cfg.qrcode_ecc_level = ESP_QRCODE_ECC_MED;
  esp_qrcode_generate(&cfg, ("http://" + ip + "/").c_str());

  int y = qrBottom + 12;
  tft.drawString("or open", SCREEN_W / 2, y);
  tft.setFreeFont(&FreeSansBold12pt7b);
  tft.setTextColor(SPOTIFY_GREEN);
  tft.drawString(ip, SCREEN_W / 2, y + 22);
  tft.setFreeFont(&FreeSans9pt7b);
  tft.setTextColor(TFT_LIGHTGREY);
  tft.drawString("deskplayer.local", SCREEN_W / 2, y + 52);
  tft.setTextColor(TFT_DARKGREY);
  tft.drawString("Your phone must be on the same Wi-Fi", SCREEN_W / 2, SCREEN_H - 46);
  if (hasAccount) tft.drawString("Press BOOT to go back", SCREEN_W / 2, SCREEN_H - 24);
  tft.setTextDatum(TL_DATUM);
}

void showAccountPage() {
  xSemaphoreTake(tftLock, portMAX_DELAY);
  closeGif();
  page = PAGE_ACCOUNT;
  drawAccountPage();
  xSemaphoreGive(tftLock);
}

// Joins whichever saved network is in range. If none is, or addNetwork is set,
// opens the DeskPlayer-Setup hotspot with a captive portal for adding a network;
// tapping Exit there keeps the saved ones. Restarts if nobody finishes within
// PORTAL_TIMEOUT_S. Then asks for a Spotify sign-in if there's no account yet,
// or offers to switch accounts when the button was held.
void setupWiFi(bool addNetwork) {
  WiFiManager wm;
  std::vector<const char*> menu = {"wifi", "exit"};
  wm.setMenu(menu);
  wm.setConfigPortalTimeout(PORTAL_TIMEOUT_S);
  wm.setConnectTimeout(15);
  wm.setConnectRetries(3);  // the router sometimes refuses the first attempt
  wm.setAPCallback([](WiFiManager*) {
    WiFi.setTxPower(WIFI_POWER_8_5dBm);
    Serial.printf("Setup portal open: join %s, then browse to %s\n", SETUP_AP, WiFi.softAPIP().toString().c_str());
    showStatus("Connect to DeskPlayer-Setup on your phone", "",
               "Then tap Configure WiFi and pick your network. Closes in 3 minutes.");
  });

  WiFi.mode(WIFI_STA);
  WiFi.setTxPower(WIFI_POWER_8_5dBm);  // full power browns out weak USB supplies
  bool ok = false;
  if (addNetwork) {
    Serial.println("Button held at boot: opening the setup portal to add a network");
    wm.resetSettings();  // only the network WiFiManager tries; the saved list stays
    ok = wm.startConfigPortal(SETUP_AP);
  } else {
    showLoading("Connecting to Wi-Fi...", "");
    for (int i = 0; i < 3 && savedCount && !ok; i++) ok = wifiMulti.run(15000) == WL_CONNECTED;
    // Nothing saved in range: try the network WiFiManager last used, then the portal
    if (!ok) ok = wm.autoConnect(SETUP_AP);
  }
  if (!ok && savedCount) {  // portal exited or timed out: fall back to a saved network
    showLoading("Connecting to Wi-Fi...", "");
    WiFi.mode(WIFI_STA);
    ok = wifiMulti.run(15000) == WL_CONNECTED;
  }
  if (!ok) restartAfterTimeout();
  WiFi.setTxPower(WIFI_POWER_8_5dBm);
  WiFi.setAutoReconnect(true);
  rememberNetwork(WiFi.SSID(), WiFi.psk());

  String ip = WiFi.localIP().toString();
  Serial.printf("Connected to %s, IP %s\n", WiFi.SSID().c_str(), ip.c_str());
  showStatus("Connected", ip, WiFi.SSID());
  delay(1500);
}

// Later drops: rejoin whichever saved network is in range
void waitForWiFi() {
  Serial.print("Wi-Fi lost, reconnecting");
  while (wifiMulti.run(10000) != WL_CONNECTED) {  // the router may refuse; keep trying
    Serial.print('.');
    delay(1000);
  }
  Serial.printf("\nReconnected, IP %s\n", WiFi.localIP().toString().c_str());
}

// The BOOT button adds a Wi-Fi network when held for a second just after power-up.
// (Holding it *while* pressing EN or plugging in starts the flasher instead.)
bool buttonHeldAtBoot() {
  showLoading("Starting...", "Hold BOOT now to add a Wi-Fi network");
  uint32_t start = millis(), heldSince = 0;
  while (millis() - start < 2500) {
    if (digitalRead(BOOT_BUTTON) == LOW) {
      if (!heldSince) heldSince = millis();
      if (millis() - heldSince >= 1000) return true;
    } else {
      heldSince = 0;
    }
    delay(10);
  }
  return false;
}

bool refreshAccessToken() {
  WiFiClientSecure client;
  client.setInsecure();  // starter only: skips TLS certificate checks
  HTTPClient http;
  http.begin(client, "https://accounts.spotify.com/api/token");
  http.setAuthorization(SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET);
  http.addHeader("Content-Type", "application/x-www-form-urlencoded");
  int code = http.POST("grant_type=refresh_token&refresh_token=" + refreshToken);
  String body = http.getString();
  http.end();
  if (code != 200) {
    Serial.printf("Token refresh failed: %d %s\n", code, body.c_str());
    return false;
  }
  JsonDocument doc;
  if (deserializeJson(doc, body)) return false;
  accessToken = doc["access_token"].as<String>();
  tokenTtlMs = (doc["expires_in"] | 3600) * 1000UL - 60000;  // refresh a minute early
  tokenFetchedAt = millis();
  Serial.println("Got access token");
  return true;
}

bool tokenValid() {
  return accessToken.length() && millis() - tokenFetchedAt < tokenTtlMs;
}

String urlEncode(const String& s) {
  const char* hex = "0123456789ABCDEF";
  String out;
  for (size_t i = 0; i < s.length(); i++) {
    uint8_t c = s[i];
    if (isalnum(c) || c == '-' || c == '_' || c == '.' || c == '~') out += (char)c;
    else if (c == ' ') out += '+';
    else {
      out += '%';
      out += hex[c >> 4];
      out += hex[c & 15];
    }
  }
  return out;
}

// "Song (feat. X) - Remix" -> "Song", which GetSongBPM matches far more often
String cleanTitle(String t) {
  for (const char* sep : {" (", " - ", " ["}) {
    int i = t.indexOf(sep);
    if (i > 0) t = t.substring(0, i);
  }
  return t;
}

// Spotify no longer offers tempo to new apps. ReccoBeats looks it up by Spotify
// track ID (exact, no key); GetSongBPM by title/artist is the fallback. 0 = unknown.
int fetchBpm(const String& trackId, const String& title, const String& artist) {
  int result = fetchBpmReccoBeats(trackId);
  if (!result) result = fetchBpmGetSongBpm(title, artist);
  Serial.printf("BPM: %d", result);
  // Databases often report double-time (hip-hop at 186 instead of the 93 you'd
  // dance to), and the dance looks frantic that fast, so fold it into range
  while (result > 160) result /= 2;
  Serial.printf(", dancing at %d\n", result);
  return result;
}

int fetchBpmReccoBeats(const String& trackId) {
  if (trackId.isEmpty()) return 0;
  WiFiClientSecure client;
  client.setInsecure();
  HTTPClient http;
  http.begin(client, "https://api.reccobeats.com/v1/audio-features?ids=" + trackId);
  int code = http.GET();
  String body = code == 200 ? http.getString() : String();
  http.end();
  if (code != 200) {
    Serial.printf("ReccoBeats lookup failed: %d\n", code);
    return 0;
  }
  // {"content":[{"tempo":132.85,...}]}, or an empty list when it doesn't know the track
  JsonDocument filter;
  filter["content"][0]["tempo"] = true;
  JsonDocument doc;
  if (deserializeJson(doc, body, DeserializationOption::Filter(filter))) return 0;
  return lroundf(doc["content"][0]["tempo"] | 0.0f);
}

int fetchBpmGetSongBpm(const String& title, const String& artist) {
  if (!strlen(GETSONGBPM_API_KEY)) return 0;
  WiFiClientSecure client;
  client.setInsecure();
  HTTPClient http;
  http.begin(client, String("https://api.getsong.co/search/?api_key=") + GETSONGBPM_API_KEY +
                         "&type=both&lookup=" + urlEncode("song:" + cleanTitle(title) + " artist:" + artist));
  int code = http.GET();
  String body = code == 200 ? http.getString() : String();
  http.end();
  if (code != 200) {
    Serial.printf("GetSongBPM lookup failed: %d\n", code);
    return 0;
  }

  // A match is {"search":[{"tempo":"120",...}]}; no match is {"search":{"error":...}}
  JsonDocument filter;
  filter["search"][0]["tempo"] = true;
  JsonDocument doc;
  if (deserializeJson(doc, body, DeserializationOption::Filter(filter))) return 0;
  JsonVariant tempo = doc["search"][0]["tempo"];
  return tempo.is<const char*>() ? atoi(tempo.as<const char*>()) : tempo.as<int>();
}

// Word-wrap s into at most maxLines lines of maxW pixels in the current font,
// ending with "..." when it doesn't all fit. Returns the number of lines.
int wrapText(const String& s, int maxW, int maxLines, String* lines) {
  int n = 0;
  String rest = s;
  rest.trim();
  while (rest.length() && n < maxLines) {
    int end = rest.length();
    while (end > 1 && tft.textWidth(rest.substring(0, end)) > maxW) end--;
    if (end < (int)rest.length()) {  // break at a space when there is one
      int sp = rest.lastIndexOf(' ', end);
      if (sp > 0) end = sp;
    }
    lines[n++] = rest.substring(0, end);
    rest = rest.substring(end);
    rest.trim();
  }
  if (rest.length() && n) {
    String& last = lines[n - 1];
    while (last.length() && tft.textWidth(last + "...") > maxW) last.remove(last.length() - 1);
    last.trim();
    last += "...";
  }
  return n;
}

// Fill everything except the art itself with the tinted background
void fillBackground() {
  int artRight = ART_X + ART_SIZE, artBottom = ART_Y + ART_SIZE;
  tft.fillRect(0, 0, tft.width(), ART_Y, panelBg);
  tft.fillRect(0, artBottom, tft.width(), tft.height() - artBottom, panelBg);
  tft.fillRect(0, ART_Y, ART_X, ART_SIZE, panelBg);
  tft.fillRect(artRight, ART_Y, tft.width() - artRight, ART_SIZE, panelBg);
}

void drawInfo(const String& title, const String& artist) {
  stopLoading();
  fillBackground();
  tft.setTextDatum(TL_DATUM);
  String lines[5];

  // Label row: "NOW PLAYING" on the left, play state on the right
  tft.setTextFont(2);
  tft.setTextColor(TFT_LIGHTGREY);  // one colour = transparent background
  tft.drawString("NOW PLAYING", TEXT_X, TEXT_Y);
  const char* state = isPlaying ? "Playing" : "Paused";
  int right = TEXT_X + TEXT_W;
  tft.fillCircle(right - tft.textWidth(state) - 9, TEXT_Y + 8, 4, isPlaying ? SPOTIFY_GREEN : TFT_DARKGREY);
  tft.setTextColor(isPlaying ? TFT_WHITE : TFT_LIGHTGREY);
  tft.setTextDatum(TR_DATUM);
  tft.drawString(state, right, TEXT_Y);
  tft.setTextDatum(TL_DATUM);

  // Title (up to 3 lines), then artists in whatever space is left above the art
  int y = TEXT_Y + 20;
  tft.setFreeFont(&FreeSansBold12pt7b);
  tft.setTextColor(TFT_WHITE);
  int n = wrapText(title, TEXT_W, 3, lines);
  for (int i = 0; i < n; i++, y += tft.fontHeight()) tft.drawString(lines[i], TEXT_X, y);

  y += 4;
  tft.setFreeFont(&FreeSans9pt7b);
  tft.setTextColor(TFT_LIGHTGREY);
  int artistLines = constrain((WAVE_Y - 4 - y) / tft.fontHeight(), 1, 5);
  n = wrapText(artist, TEXT_W, artistLines, lines);
  for (int i = 0; i < n; i++, y += tft.fontHeight()) tft.drawString(lines[i], TEXT_X, y);

  memset(barH, 0, sizeof(barH));  // the background fill wiped the wave; redraw it all
  drawWave();
}

// Decorative wave under the artists. Spotify doesn't expose live audio levels,
// so the bars are generated: moving while a track plays, flat when paused.
// Only the pixels that changed since the last frame are drawn.
void drawWave() {
  int x0 = TEXT_X + (TEXT_W - (BAR_COUNT * (BAR_W + BAR_GAP) - BAR_GAP)) / 2;
  int mid = WAVE_Y + WAVE_H / 2;
  float t = millis() / 1000.0f;
  uint16_t color = isPlaying ? SPOTIFY_GREEN : TFT_DARKGREY;
  for (int i = 0; i < BAR_COUNT; i++) {
    int h = 2;
    if (isPlaying) {
      float env = 0.35f + 0.65f * sinf(PI * (i + 0.5f) / BAR_COUNT);  // taller in the middle
      float v = 0.55f + 0.3f * sinf(i * 0.45f + t * 6.0f) + 0.15f * sinf(i * 1.3f - t * 9.1f);
      h = max(2, (int)(v * env * WAVE_H)) & ~1;  // even heights keep bars centred
    }
    int old = barH[i];
    if (h == old) continue;
    int x = x0 + i * (BAR_W + BAR_GAP);
    if (h > old) {
      tft.fillRect(x, mid - h / 2, BAR_W, h, color);
    } else {  // shrink: clear the strips above and below the new height
      int d = (old - h) / 2;
      tft.fillRect(x, mid - old / 2, BAR_W, d, panelBg);
      tft.fillRect(x, mid + h / 2, BAR_W, d, panelBg);
    }
    barH[i] = h;
  }
}

bool drawArt(String url) {
  // Album art is public, so fetch it over plain HTTP: a TLS connection holds
  // ~100 KB of RAM, which leaves no room for covers over ~55 KB
  url.replace("https://", "http://");
  WiFiClient client;
  HTTPClient http;
  http.begin(client, url);
  int code = http.GET();
  int len = http.getSize();
  if (code != 200 || len <= 0 || len > 150000) {
    Serial.printf("Art download failed: HTTP %d, %d bytes\n", code, len);
    http.end();
    return false;
  }
  uint8_t* buf = (uint8_t*)(psramFound() ? ps_malloc(len) : malloc(len));
  if (!buf) {
    Serial.printf("Out of memory for art: need %d, free %u, largest block %u\n", len, ESP.getFreeHeap(),
                  ESP.getMaxAllocHeap());
    http.end();
    return false;
  }

  WiFiClient* stream = http.getStreamPtr();
  int got = 0;
  uint32_t start = millis();
  while (got < len && (http.connected() || stream->available()) && millis() - start < 10000) {
    size_t avail = stream->available();
    if (avail) got += stream->readBytes(buf + got, min((size_t)(len - got), avail));
    else delay(1);
  }
  http.end();

  bool ok = got == len;
  if (ok) {
    uint16_t w, h;
    TJpgDec.getJpgSize(&w, &h, buf, len);
    uint8_t scale = 1;
    while (w / scale > ART_SIZE && scale < 8) scale *= 2;
    TJpgDec.setJpgScale(scale);
    xSemaphoreTake(tftLock, portMAX_DELAY);
    ok = page == PAGE_NOW_PLAYING;  // the user may have switched pages mid-download
    if (ok) {
      stopLoading();
      tft.fillRect(ART_X, ART_Y, ART_SIZE, ART_SIZE, TFT_BLACK);
      sumR = sumG = sumB = sumN = 0;
      TJpgDec.drawJpg(ART_X, ART_Y, buf, len);
      if (sumN) {  // darken the average to ~40% so white text stays readable
        uint16_t r = sumR / sumN * 2 / 5, g = sumG / sumN * 2 / 5, b = sumB / sumN * 2 / 5;
        panelBg = (r << 11) | (g << 5) | b;
      }
    }
    xSemaphoreGive(tftLock);
    if (ok) Serial.printf("Drew %ux%u art (scale 1/%u), free heap %u\n", w, h, scale, ESP.getFreeHeap());
  } else {
    Serial.printf("Art download incomplete: %d/%d bytes\n", got, len);
  }
  free(buf);
  return ok;
}

void fetchNowPlaying() {
  if (forceRedraw) {
    forceRedraw = false;
    currentArtUrl = "";
    lastInfo = "";
  }
  if (refreshToken.isEmpty()) return;  // waiting for the Spotify page
  if (!tokenValid() && !refreshAccessToken()) return;

  WiFiClientSecure client;
  client.setInsecure();
  HTTPClient http;
  http.begin(client, "https://api.spotify.com/v1/me/player/currently-playing");
  http.addHeader("Authorization", "Bearer " + accessToken);
  int code = http.GET();

  if (code == 204) {  // nothing playing
    http.end();
    Serial.println("Nothing playing");
    return;
  }
  if (code == 401) {  // token rejected; get a fresh one next poll
    accessToken = "";
    http.end();
    return;
  }
  if (code != 200) {
    Serial.printf("currently-playing failed: %d\n", code);
    http.end();
    return;
  }
  String body = http.getString();
  http.end();

  // Keep only the fields we use; the full response is several KB
  JsonDocument filter;
  filter["is_playing"] = true;
  filter["item"]["id"] = true;
  filter["item"]["name"] = true;
  filter["item"]["artists"][0]["name"] = true;
  filter["item"]["album"]["images"][0]["url"] = true;
  filter["item"]["album"]["images"][0]["width"] = true;

  JsonDocument doc;
  DeserializationError err = deserializeJson(doc, body, DeserializationOption::Filter(filter));
  if (err) {
    Serial.printf("JSON error: %s\n", err.c_str());
    return;
  }
  if (doc["item"].isNull()) {
    Serial.println("No track info (ad or podcast?)");
    return;
  }

  isPlaying = doc["is_playing"] | false;
  String title = doc["item"]["name"] | "";
  String firstArtist = doc["item"]["artists"][0]["name"] | "";
  String artist;
  for (JsonObject a : doc["item"]["artists"].as<JsonArray>()) {
    if (artist.length()) artist += ", ";
    artist += a["name"] | "";
  }

  // New song: look up its tempo for the GIF page
  String trackId = doc["item"]["id"] | "";
  String key = trackId + "|" + title + "|" + firstArtist;
  if (key != bpmKey) {
    int newBpm = fetchBpm(trackId, title, firstArtist);
    xSemaphoreTake(tftLock, portMAX_DELAY);
    bpmKey = key;
    bpm = newBpm;
    curTitle = title;
    curArtist = artist;
    gifPageDirty = true;
    xSemaphoreGive(tftLock);
  }

  // Spotify usually lists 640, 300 and 64 px images; take the 300 px one
  JsonArray images = doc["item"]["album"]["images"];
  String artUrl;
  for (JsonObject img : images) {
    if (img["width"] == ART_SIZE) {
      artUrl = img["url"].as<String>();
      break;
    }
  }
  if (artUrl.isEmpty() && images.size()) artUrl = images[0]["url"].as<String>();

  // Art first: it sets the background colour the text panel is drawn on.
  // Skipped on the GIF page; switching back forces a full redraw.
  bool newArt = page == PAGE_NOW_PLAYING && artUrl.length() && artUrl != currentArtUrl && drawArt(artUrl);
  if (newArt) currentArtUrl = artUrl;

  String info = title + "|" + artist + "|" + isPlaying;
  if (newArt || info != lastInfo) {
    xSemaphoreTake(tftLock, portMAX_DELAY);
    if (page == PAGE_NOW_PLAYING) {
      drawInfo(title, artist);
      showWave = true;
    }
    xSemaphoreGive(tftLock);
    lastInfo = info;
    Serial.printf("%s - %s (%s)\n", title.c_str(), artist.c_str(), isPlaying ? "playing" : "paused");
  }
}

// ---- GIF page ----

// Browsers show GIF frames with a 0-10 ms delay at 100 ms; do the same
int frameDelay(int ms) {
  return ms < 20 ? 100 : ms;
}

// Called by AnimatedGIF for each decoded line; draws it centred on screen
void gifDraw(GIFDRAW* d) {
  int y = gifY + d->iY + d->y;
  int x = gifX + d->iX;
  int w = min(d->iWidth, SCREEN_W - x);
  if (y < 0 || y >= SCREEN_H || w < 1) return;
  uint8_t* s = d->pPixels;
  if (d->ucDisposalMethod == 2) {  // "restore to background"
    for (int i = 0; i < w; i++)
      if (s[i] == d->ucTransparent) s[i] = d->ucBackground;
    d->ucHasTransparency = 0;
  }
  if (!d->ucHasTransparency) {
    for (int i = 0; i < w; i++) gifLine[i] = d->pPalette[s[i]];
    tft.setAddrWindow(x, y, w, 1);
    tft.pushPixels(gifLine, w);
    return;
  }
  // Transparent pixels keep what's already on screen: push only the opaque runs
  for (int i = 0; i < w;) {
    while (i < w && s[i] == d->ucTransparent) i++;
    int start = i, n = 0;
    while (i < w && s[i] != d->ucTransparent) gifLine[n++] = d->pPalette[s[i++]];
    if (n) {
      tft.setAddrWindow(x + start, y, n, 1);
      tft.pushPixels(gifLine, n);
    }
  }
}

void gifSkipDraw(GIFDRAW*) {}

bool openGif(GIF_DRAW_CALLBACK* draw) {
  if (!gif) gif = new (std::nothrow) AnimatedGIF;
  if (!gif) return false;
  gif->begin(BIG_ENDIAN_PIXELS);
  if (!gif->open((uint8_t*)gifData, sizeof(gifData), draw)) {
    delete gif;
    gif = nullptr;
    return false;
  }
  // Centre it in the space between the title (top) and the BPM (bottom)
  gifX = (SCREEN_W - gif->getCanvasWidth()) / 2;
  gifY = 255 - gif->getCanvasHeight() / 2;
  return true;
}

void closeGif() {
  if (!gif) return;
  gif->close();
  delete gif;
  gif = nullptr;
}

// Decode every frame once without drawing to learn how long one loop lasts
uint32_t measureGifLoop() {
  if (!openGif(gifSkipDraw)) return 0;
  uint32_t total = 0;
  int ms, more, frames = 0;
  do {
    more = gif->playFrame(false, &ms);
    total += frameDelay(ms);
  } while (more > 0 && ++frames < 1000);
  closeGif();
  return total;
}

void drawGifPage() {
  stopLoading();
  // Match the GIF's own background, with text that stays readable on it
  tft.fillScreen(GIF_BG_COLOR);
  tft.setTextDatum(TC_DATUM);
  String lines[2];
  int y = 12;
  tft.setFreeFont(&FreeSansBold12pt7b);
  tft.setTextColor(GIF_BG_LIGHT ? TFT_BLACK : TFT_WHITE);
  int n = wrapText(curTitle, TEXT_W, 2, lines);
  for (int i = 0; i < n; i++, y += tft.fontHeight()) tft.drawString(lines[i], SCREEN_W / 2, y);
  tft.setFreeFont(&FreeSans9pt7b);
  tft.setTextColor(GIF_BG_LIGHT ? TFT_DARKGREY : TFT_LIGHTGREY);
  if (wrapText(curArtist, TEXT_W, 1, lines)) tft.drawString(lines[0], SCREEN_W / 2, y);

  tft.setFreeFont(&FreeSansBold18pt7b);
  tft.setTextColor(bpm ? SPOTIFY_GREEN : TFT_DARKGREY);
  tft.drawString(bpm ? String(bpm) + " BPM" : String("BPM unknown"), SCREEN_W / 2, SCREEN_H - 56);
  tft.setTextDatum(TL_DATUM);
}

void playGifFrame() {
  if ((int32_t)(millis() - nextFrameAt) < 0) return;
  int ms = 0;
  xSemaphoreTake(tftLock, portMAX_DELAY);
  if (gifPageDirty) {  // new song: redraw the labels and restart from a full first frame
    gifPageDirty = false;
    drawGifPage();
    gif->reset();
  }
  tft.startWrite();
  int more = gif->playFrame(false, &ms);
  tft.endWrite();
  xSemaphoreGive(tftLock);
  if (more <= 0) gif->reset();

  // Stretch or squeeze every frame so one loop lasts GIF_BEATS_PER_LOOP beats
  uint32_t wait = frameDelay(ms);
  if (bpm > 0 && gifLoopMs) wait = wait * (GIF_BEATS_PER_LOOP * 60000UL / bpm) / gifLoopMs;
  nextFrameAt += max(wait, (uint32_t)10);
  if ((int32_t)(millis() - nextFrameAt) > 250) nextFrameAt = millis();  // fell behind; don't race to catch up
}

// ---- Pages and touch ----

void switchPage() {
  xSemaphoreTake(tftLock, portMAX_DELAY);
  stopLoading();
  if (page == PAGE_ACCOUNT && refreshToken.isEmpty()) {
    xSemaphoreGive(tftLock);  // nothing to go back to yet
    return;
  }
  if (page == PAGE_NOW_PLAYING) {
    if (openGif(gifDraw)) {
      page = PAGE_GIF;
      gifPageDirty = false;
      drawGifPage();
      nextFrameAt = millis();
    } else {
      Serial.println("Not enough memory to open the GIF");
    }
  } else {
    closeGif();
    page = PAGE_NOW_PLAYING;
    tft.fillScreen(panelBg);
    forceRedraw = true;
  }
  xSemaphoreGive(tftLock);
  Serial.printf("Page: %s, free heap %u\n", page == PAGE_GIF ? "GIF" : "now playing", ESP.getFreeHeap());
  if (page == PAGE_NOW_PLAYING) xTaskNotifyGive(spotifyTaskHandle);  // redraw now, not at the next poll
}

void checkButton() {
  static uint32_t downAt = 0;
  static bool held = false;
  bool down = digitalRead(BOOT_BUTTON) == LOW;
  if (down && !downAt) {
    downAt = millis();
    held = false;
  } else if (down && !held && millis() - downAt >= 1500) {
    held = true;
    if (page != PAGE_ACCOUNT) showAccountPage();
  } else if (!down && downAt) {
    if (!held && millis() - downAt > 30) switchPage();  // ignore contact bounce
    downAt = 0;
  }
}

// A tap anywhere switches pages; no calibration needed since position doesn't matter
void checkTouch() {
#ifdef TOUCH_CS
  static uint32_t lastCheck = 0, lastTap = 0;
  static bool wasDown = false;
  if (!touchOk || millis() - lastCheck < 30) return;
  lastCheck = millis();
  xSemaphoreTake(tftLock, portMAX_DELAY);
  bool down = tft.getTouchRawZ() > TOUCH_Z_MIN;
  xSemaphoreGive(tftLock);
  if (down && !wasDown && millis() - lastTap > 400) {
    lastTap = millis();
    switchPage();
  }
  wasDown = down;
#endif
}

void setupTouch() {
#ifdef TOUCH_CS
  // Nobody is touching at boot, so constant "pressed" readings mean touch isn't wired
  int pressed = 0;
  for (int i = 0; i < 10; i++) {
    if (tft.getTouchRawZ() > TOUCH_Z_MIN) pressed++;
    delay(5);
  }
  touchOk = pressed < 5;
  Serial.println(touchOk ? "Touch ready: tap to switch pages" : "Touch reads as pressed; check T_ wiring. Page switching off");
#else
  Serial.println("TOUCH_CS isn't set in TFT_eSPI's User_Setup.h; page switching off");
#endif
}

void spotifyTask(void*) {
  for (;;) {
    if (WiFi.status() != WL_CONNECTED) waitForWiFi();
    handleSignIn();
    fetchNowPlaying();
    if (loadingActive && page == PAGE_NOW_PLAYING) {  // first poll had nothing to draw
      showStatus("Nothing playing", "", "Play something on Spotify and it shows up here");
      currentArtUrl = "";  // so the next song redraws over this whole screen
      lastInfo = "";
    }
    ulTaskNotifyTake(pdTRUE, pdMS_TO_TICKS(POLL_MS));  // wakes early after a page switch
  }
}

void setup() {
  Serial.begin(115200);
  Serial.printf("\nSpotifyDesk, PSRAM: %u bytes\n", ESP.getPsramSize());
  tft.init();
  tft.setRotation(2);  // portrait, 320x480; use 0 if it's upside down
  tft.fillScreen(TFT_BLACK);
  TJpgDec.setSwapBytes(true);
  TJpgDec.setCallback(tftOutput);
  tftLock = xSemaphoreCreateMutex();
  xTaskCreatePinnedToCore(spinnerTask, "spinner", 3072, nullptr, 1, nullptr, 0);
  pinMode(BOOT_BUTTON, INPUT_PULLUP);
  bool addNetwork = buttonHeldAtBoot();
  setupTouch();
  gifLoopMs = measureGifLoop();
  Serial.printf("GIF loop: %u ms, %d beat(s)\n", gifLoopMs, GIF_BEATS_PER_LOOP);
  prefs.begin("deskplayer");
  refreshToken = prefs.getString("refresh", "");
#ifdef SPOTIFY_REFRESH_TOKEN  // one-time seed: flash once with it in secrets.h, then remove it
  if (refreshToken.isEmpty()) {
    refreshToken = SPOTIFY_REFRESH_TOKEN;
    prefs.putString("refresh", refreshToken);
    Serial.println("Copied the refresh token from secrets.h to flash");
  }
#endif
  Serial.printf("Spotify refresh token: %s\n", refreshToken.length() ? "loaded from flash" : "not set");
  loadNetworks();
  setupWiFi(addNetwork);
  if (refreshToken.length()) {
    showLoading("Loading Spotify...", "");
    refreshAccessToken();
  } else {
    showAccountPage();
  }  // first run: stays up until someone signs in
  xTaskCreatePinnedToCore(spotifyTask, "spotify", 12288, nullptr, 1, &spotifyTaskHandle, 0);
  setupWebServer();
}

// loop() handles touch and animation; all network work happens in spotifyTask
void loop() {
  server.handleClient();
  checkButton();
  checkTouch();
  if (page == PAGE_GIF) {
    playGifFrame();
  } else if (page == PAGE_NOW_PLAYING && showWave && isPlaying && millis() - lastFrame >= WAVE_FRAME_MS) {
    lastFrame = millis();
    xSemaphoreTake(tftLock, portMAX_DELAY);
    drawWave();
    xSemaphoreGive(tftLock);
  }
  delay(2);
}
