#!/usr/bin/env python3
"""Convert a GIF into SpotifyDesk/gif_data.h for the BPM page.

    python3 tools/gif2h.py my.gif --beats 4

--beats is how many beats one loop of the GIF should last, so the sketch can
stretch it to the song's tempo: a single bounce or head-nod is 1, a
left-right-left-right dance step is 4.

Frames are flattened onto black and shrunk to fit --max pixels (default 240).
Smaller GIFs decode faster, so fast songs stay in sync.
"""
import argparse
import io
import pathlib

from PIL import Image, ImageSequence

ROOT = pathlib.Path(__file__).resolve().parent.parent

p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
p.add_argument("gif")
p.add_argument("--beats", type=int, default=1, help="beats per loop of the GIF (default 1)")
p.add_argument("--max", type=int, default=240, help="max width/height in pixels (default 240)")
p.add_argument("--out", default=str(ROOT / "SpotifyDesk" / "gif_data.h"))
args = p.parse_args()

src = Image.open(args.gif)
frames, durations = [], []
for frame in ImageSequence.Iterator(src):
    rgba = frame.convert("RGBA")
    flat = Image.new("RGB", rgba.size, (0, 0, 0))
    flat.paste(rgba, mask=rgba.getchannel("A"))
    flat.thumbnail((args.max, args.max), Image.LANCZOS)
    frames.append(flat.quantize(colors=256))
    durations.append(frame.info.get("duration") or 100)

buf = io.BytesIO()
frames[0].save(buf, format="GIF", save_all=True, append_images=frames[1:],
               duration=durations, loop=0, disposal=1)
data = buf.getvalue()

w, h = frames[0].size
name = pathlib.Path(args.gif).name
out = [
    f"// Generated by tools/gif2h.py from {name}: {w}x{h}, {len(frames)} frames,",
    f"// {sum(durations)} ms per loop at its own speed, {len(data)} bytes",
    "#pragma once",
    "",
    f"#define GIF_BEATS_PER_LOOP {args.beats}",
    "",
    "const uint8_t gifData[] PROGMEM = {",
]
for i in range(0, len(data), 16):
    out.append("  " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
out.append("};")
pathlib.Path(args.out).write_text("\n".join(out) + "\n")

print(f"{args.out}: {w}x{h}, {len(frames)} frames, {len(data) / 1024:.0f} KB, {args.beats} beat(s) per loop")
if len(data) > 1_500_000:
    print("warning: over ~1.5 MB won't fit in flash next to the sketch; try a smaller --max")
